[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/app"
  to = "/app/"
  status = 301

[functions]
  directory = "netlify/functions"

[functions."ask"]
  timeout = 26
